### ISSUE TITLE
Update the pack

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Revelation-2#162] opened 2019-01-06 01:27 UTC
Update the pack. Make sure you actually update the mods too. 

Aroma1997 over a year out of date.
Industrialforegoing almost a year out of date.
You updated AE2 but not Wireless Crafting Terminal and now Wireless Crafting Terminal doesn't work.
And much much more.

You are the FTB Pack Lead Developer and this is how you set an example as a leader. You release this trash then ignore everyone?

Get your shit together, comrade.

**Comment by happypsion** [comment] 2019-01-06 18:20
Astral Sorcery has bugs with SpongeForge and server disconnects that have been fixed since the last update. Can't find it in their changelog, but their bug tracker marked it as fixed and I confirmed there isn't a problem with newer versions.

OpenComputers has optimization ("Misc: Greatly improved Lua execution speed (asiekierka)
That means OC now executes Lua code roughly 70% faster than before." and fixes compatibility with project red.

It's looking like this pack is abandonware, not living up to the advertisement of having ongoing updates.

**Closed as completed** 2019-01-09 17:10 UTC

**Comment by Shybella** [comment] 2019-01-09 17:33
I asked him to take look. https://i.imgur.com/0DwXp9e.png

He closed the https://github.com/FTBTeam/FTB-Revelation-2/issues/161 and says to go bug the mod dev. The mod is updated and the devs do a very good job on Aroma, it's just not running any of the latest versions in Revelation, because, he's a bad pack maintainer, he doesn't care, he doesn't even bother to read. 

Same goes for Industrialforegoing. He thinks the mod is out of date and and thus that's his reason, although the mod is updated and he's blaming his
