### ISSUE TITLE
2.0.0 version causing rampent lag, game stuttering (Single Player)

### ISSUE THREAD

**Issue by SgtQuote** [FTBTeam/FTB-Revelation-2#30] opened 2018-06-16 18:21 UTC
* **Modpack Version**: 2.0.0

* **Issue**: The game stutters consistently, in single player. every few seconds the game will halt and start again. I thought it was world gen, but after waiting for nearly 30 minutes for the lag to clear up, it did not. This happened in many different worlds, with low chunk rendering view distance, and did not happen with the previous versions of the mudpack. I have over 4 GB of RAM, and am using the proper version of Java.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Repeatable with many new worlds, my old one, and in the same world after saving and reloading, or after waiting for half an hour.

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by PonyWarrior** [comment] 2018-06-19 16:14
Having the same issue

**Comment by tfox83** [comment] 2018-06-20 17:55
I will need a log.  I am not able to reproduce this across many computers including my beta testers.

**Comment by DarkenMoon97** [comment] 2018-06-20 20:31
Might be related to JourneyMap, my server will lag if anyone changes dimensions. The server will log spam about `Undefined discriminator for message type DimensionPermissionPacket in channel jm_dim_permission`.

Might be related:
https://github.com/TeamJM/journeymap/issues/42

**Comment by CuriousHP** [comment] 2018-06-27 18:23
MIght not be actual anymore but I'm going to comment anyways. I'm experiencing similiar issue with game stutter in multiplayer (We're playing on 2.1.0 version), I have 6 GB of ram allocated to the game and i'm using latest version of Java (checked that before commenting). But the problem I'm seeing is that for some reason memory fills up stupidly fast.

**Comment by tfox83** [comment] 2018-06-29 14:55
I am closing due to no log so I have no idea what is causing your Java to fill up so fast.  I am not able to reproduce this across multiple test PCs.

**Closed by tfox83** 2018-06-29 14:55 UTC
