### ISSUE TITLE
2.6.0 WirelessCraftingTerminal Outdated - Version incompatible with Applied Energistics 2

### ISSUE THREAD

**Issue by Skaronator** [FTBTeam/FTB-Revelation-2#135] opened 2018-11-14 17:57 UTC
* **Modpack Version**: 2.6.0

* **Issue**: The latest update of this mod pack upgraded AE2 from RV5 to RV6 which mean that most AE relevant mods need a update as well. Currently Revelation 2.6.0 use the WirelessCraftingTerminal-1.12.2-3.9.68.jar (RV5) release which is for RV5 and not RV6. The issue I've noticed that you can't shift + click on a item to transfer it to ME or vise versa.

I'm using the WirelessCraftingTerminal-1.12.2-3.10.82.jar release since a few weeks with AE2-rv6.stable.1 and it works fine.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: [Wireless Crafting Terminal](https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files)

* **Known Fix**: Upgrade to WirelessCraftingTerminal-1.12.2-3.10.82.jar - (Also upgrade AE2 to stable 4 while you're at it)

**Comment by amisme** [comment] 2018-11-30 06:16
Issue is present in the 2.6.0 version that was marked as release today. With the included version of Wireless Crafting Terminal, the wireless crafting terminal can only view items in a linked network. It cannot add or remove items, or queue crafting jobs.

**Comment by L0RIEN** [comment] 2018-11-30 18:36
> Issue is present in the 2.6.0 version that was marked as release today. With the included version of Wireless Crafting Terminal, the wireless crafting terminal can only view items in a linked network. It cannot add or remove items, or queue crafting jobs.

Had that too. Crafting a new one fixed it for me. And I did craft a Universal version of it. More handy.

**Comment by amisme** [comment] 2018-12-01 01:11
I crafted a new Wireless Crafting Terminal and the issue is still present. No change when I add it to a universal terminal.

**Comment by L0RIEN** [comment] 2018-12-01 01:30
> I crafted a new Wireless Crafting Terminal and the issue is still present. No change when I add it to a universal terminal.

You have the Shit(Sneak) right click to switch to item mode then you can add and retrieve items from ME. Less convenient than before but it works.

**Comment by amisme** [comment] 2018-12-01 01:38
You're not using the Wireless Crafting Terminal at all, then. You're just using the regular Wireless Terminal from base Applied Energistics 2, from a Universal Terminal that also has the Wireless Crafting Terminal added to it.

**Comment by L0RIEN** [comment] 2018-12-01 01:54
> You're not using the Wireless Crafting Terminal at all, then. You're just using the regular Wireless Terminal from base Applied Energistics 2, from a Universal Terminal that also has the Wireless Crafting Terminal added to it.

I am it has the Infinity card installed

**Comment by Kettzer** [comment] 2018-12-02 21:02
It is a fail from the FTB Team, they update the WirelessCrafting Mod to the wrong version.
AE2 is RV6 but WCT is RV5, they dont work togeter. if you can switch to WCT RV6 its work perfekt

**Comment by Shybella** [comment] 2018-12-29 19:15
I've slowly started losing hope with FTB. Aroma1997 in this pack is over a year out of date. They just don't care. You see the lack of care.

**Comment by tfox83** [comment] 2019-01-09 22:06
Fixed in 2.7.0 beta.

@Shybella Aroma1997 is running latest release from July.  We do not run betas unless asked to by the dev.  If it bothers you this much go ask him to make his betas release files.

**Closed by tfox83** 2019-01-09 22:06 UTC
