### ISSUE TITLE
Recipe: Rustic tallow can't be created in all furnace types

### ISSUE THREAD

**Issue by gricey432** [FTBTeam/FTB-Revelation-2#331] opened 2019-11-09 07:12 UTC
* **Modpack Version**: 3.2.0

* **Issue**: Rustic Tallow can only be created in some furnace types (e.g. can't make in in a Thermal Expansion Redstone Furnace)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Rustic, Thermal Expansion, (possibly other mods which provide furnaces)

**Comment by ghost** [comment] 2019-11-16 06:16
seems inteded balancing

**Comment by gricey432** [comment] 2019-11-18 03:53
Not sure how it would help with balancing, since a vanilla minecraft furnace is easier to make than a redstone furnace, so it's not holding it into the later game

**Comment by ghost** [comment] 2019-11-18 05:36
so - I had a bit different answer first - but decided to load the game and do some testing myself
I also dug through the configs - to cut it down: it's not in any config or tweak
so, as far as I know, anything that can be smelted normally can be smelted in any smelter unless some specific rules prevent this - also this can be caused by mod incompatibility
just to check my asumptions I set up a quick test system with only forge, rustic, thermal and jei
when broken down to this example the tallow can only be smelted in a vanilla furnace but not in the thermal ones - so, same as in the pack
this means:
1) it's not an issue of this pack (makes this issue somewhat invalid / informative only
2) either rustic doesn't recon thermal furnace as smelter (most likely), rustic specific exclude thermal (for balancing) or thermal doesn't recon rustic (unlikely as without any tweak thermal furnaces can smelt what any other furnace can smelt)
so - I would suggest you to look over to rustic issues: https://github.com/the-realest-stu/Rustic/issues?q=is%3Aissue+thermal
seems someone already noted that rustic isn't compatible with thermal - but for some reason the author just closed it without implement compat for thermal - so, just open another issue over there and see if and what happen ...

about possible balancing: maybe it's intended as not for it's easy in the early game but it's hard in the late game as you still stuck to slow vanilla process from early game without able to speed up in the late game (I recall some OP-mod that was tweaked this way to slow its pace down)

**Closed as completed** 2021-05-31 17:55 UTC
