### ISSUE TITLE
Yellorite and Uranium not spawning 3.0.1

### ISSUE THREAD

**Issue by Frolist** [FTBTeam/FTB-Revelation-2#268] opened 2019-07-03 01:09 UTC
* **Modpack Version**: 3.0.1

* **Issue**:  yellorite and uranium not spawning 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**:  Extreme Reactors 0.1.5.66 industrial craft 2-2.8  

* **Known Fix**:

**Comment by GrumpyChunks** [comment] 2019-07-04 11:34
Duplicate of #227

**Comment by tfox83** [comment] 2019-07-22 17:34
Fixed in 3.1.0

**Closed as completed by tfox83** 2019-07-22 17:34 UTC
