### ISSUE TITLE
Crash when searching uses of "paintable" items in JEI

### ISSUE THREAD

**Issue by Hazmatik** [FTBTeam/FTB-Revelation-2#90] opened 2018-08-07 13:35 UTC
* **Modpack Version**: 2.2.0

* **Issue**: Whenever I right click any of the blocks that can be painted by the Ender IO painter (cobblestone, ender IO machines, etc.) in JEI to see the recipes they can be used in my client crashes. It seems to be related to something with fiery essence fluid (this line specifically "java.lang.RuntimeException: Fluid net.minecraftforge.fluids.Fluid@322de6c5 (fiery_essence, class net.minecraftforge.fluids.Fluid) from item 1xic2.fluid_cell@0 returned an unregistered block from getBlock(). This is a major bug in the mod that fluid belongs to.").

* **Link to Log or Crash File Paste**: https://pastebin.com/cjh5eHLX

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Ender IO, whichever mod adds fiery essence fluid

* **Known Fix**: None

**Comment by tfox83** [comment] 2018-08-15 17:13
This may of been fixed with the udpate to EnderIO in 2.4.0 beta, I am not able to reproduce this.  Please reopen if you can repeat after updating, thanks.

**Closed by tfox83** 2018-08-15 17:13 UTC
