### ISSUE TITLE
Extreme Reactor Turbine MAJOR TPS drop (20 down to 3)

### ISSUE THREAD

**Issue by xWaller19** [FTBTeam/FTB-Revelation-2#248] opened 2019-06-07 04:18 UTC
Modpack Version: 3.0.1

Issue: Big Reactos/Extreme Reactors (Legacy) turbine drops a servers TPS DRAMATICALLY when the energy buffer is full and its not exporting any of it. It almost looked like my rotor and blade RPM was "lagging" or having a huge drag on it but it was still at optimal RPM. Slowed down visually, a lot.

My Setup:
7x7x17, 80 blades, 32 Ludacrite blocks as the coils. 2000mb/t of steam

Link to Log or Crash File Paste: N/A

Is it Repeatable?: Yes, any player can do it if they have one (obviously)

Mod/s Affected: Extreme Reactors (Legacy)/ Server Performance

Known Fix: N/A

**Comment by CitiesXL2815** [comment] 2019-07-10 02:57
https://github.com/ZeroNoRyouki/BigReactors/issues/161

**Comment by tfox83** [comment] 2019-07-22 17:30
This seems to have been fixed in 3.1.0, at least I cannot reproduce it in my test world

**Closed as completed by tfox83** 2019-07-22 17:30 UTC
